import './scss/custom.scss'
import { useState } from 'react';
import TestNavbar from './components/Navbar'
import SelectDefault from './components/DefaultSelect'
import ScoresTab from './components/ScoresTabs/scoresTab'
import SettingsModal from './components/settingsModal';
import type { Tab } from './interfaces/User';

function App() {
  const [tabs, setTabs] = useState<Tab[]>([]);

  const addTab = (name: string, weight: number) => {
    const newTab: Tab = {
      id: tabs.length,
      scores: [],
      name,
      weight
    };
    setTabs([...tabs, newTab]);
  };

  const updateTabName = (id: number, name: string) => {
    setTabs(tabs.map(tab => 
      tab.id === id ? { ...tab, name } : tab
    ));
  };

  const updateTabWeight = (id: number, weight: number) => {
    setTabs(tabs.map(tab => 
      tab.id === id ? { ...tab, weight } : tab
    ));
  };

  const deleteTab = (id: number) => {
    setTabs(tabs.filter(tab => tab.id !== id));
  };

  const addScore = (tabId: number, label: string, score: number, totalScore: number) => {
    setTabs(tabs.map(tab => {
      if (tab.id === tabId) {
        const newScore = {
          id: tab.scores.length,
          score,
          totalScore,
          label
        };
        return { ...tab, scores: [...tab.scores, newScore] };
      }
      return tab;
    }));
  };

  function calculateFinalGrade(tabs: Tab[]): number {
    let finalGrade = 0;
    

    tabs.forEach(tab => {
      const tabTotal = tab.scores.reduce((sum, score) => sum + (score.score / score.totalScore) * 100, 0);
      const tabAverage = tab.scores.length > 0 ? tabTotal / tab.scores.length : 0;
      finalGrade += (tabAverage * (tab.weight / 100));
    });

    return finalGrade;
  }

  function printFinalGrade() {
    console.log("Tabs Data: ", tabs);
    console.log("Final Grade: ", calculateFinalGrade(tabs).toFixed(2));
  }

  return (
    <>
      <TestNavbar title={"Evalytics"}/>
      <div className="container mt-5 bg-body-secondary rounded-5">
        <div className="container p-5">
          <h1 className='text-center fw-bold'>Evalytics</h1>
          <span className="badge text-bg-warning mt-4 mb-4">Early Development</span>
          <p><p className='lead'>DISCLAIMER:</p> This website is an independent tool developed for simulation and educational purposes only. It is not officially affiliated with the Cebu Institute of Technology - University (CIT-U) and should not be used as a substitute for official academic records.</p>
          <p>All outputs generated by this system are ESTIMATED grades calculated based on the official CIT-U Grade Transmutation Table. This tool is intended to assist students with personal grade computations and "what-if" scenarios to determine necessary scores for passing. Final and official grades are exclusively determined by university instructors</p>
          <div className='d-flex align-items-stretch gap-3'>
            <SelectDefault />
            <SettingsModal tabs={tabs} onAddTab={addTab} />
          </div>

          <div className='justify-content-center'>
            <ScoresTab tabs={tabs} onUpdateTabName={updateTabName} onUpdateTabWeight={updateTabWeight} onDeleteTab={deleteTab} onAddScore={addScore} />
          </div>

          <div className='d-flex align-items-stretch justify-content-center mt-4'>
            <button type="button" className="btn btn-primary" onClick={printFinalGrade}>WAHHHHH</button>
          </div>

          <h1>Score is: {calculateFinalGrade(tabs).toFixed(1)}</h1>
        </div>
      </div>
    </>
  )
}

export default App